### ISSUE TITLE
Canonical Preset Should be Proper Classes

### ISSUE THREAD

**Issue by Steven-Roberts** [ComputationalScienceLaboratory/ODE-Test-Problems#110]
Let's avoid stub preset classes like https://github.com/ComputationalScienceLaboratory/ODE-Test-Problems/blob/master/toolbox/%2Botp/%2Bbrusselator/%2Bpresets/Canonical.m. We can simply call the parent class Canonical.

**Comment by AndreyAPopov** [comment]
Done for Lorenz '63 in the new docs
