### ISSUE TITLE
PopovSandu preset of L96

### ISSUE THREAD

**Issue by Steven-Roberts** [ComputationalScienceLaboratory/ODE-Test-Problems#19]
Some issues I noticed in this preset:

Is this validation really necessary?  I makes the input parsing very complicated
https://github.com/ComputationalScienceLaboratory/ODE-Test-Problems/blob/ca212220284c8c272d4951fdaae4418928ed9f73/src/%2Botp/%2Blorenz96/%2Bpresets/PopovSandu.m#L31

This can be simplified to just a `fiveDays` variable
https://github.com/ComputationalScienceLaboratory/ODE-Test-Problems/blob/ca212220284c8c272d4951fdaae4418928ed9f73/src/%2Botp/%2Blorenz96/%2Bpresets/PopovSandu.m#L39-L41

This can be simplified.  It also uses 40 variables instead of `N`
https://github.com/ComputationalScienceLaboratory/ODE-Test-Problems/blob/ca212220284c8c272d4951fdaae4418928ed9f73/src/%2Botp/%2Blorenz96/%2Bpresets/PopovSandu.m#L43

This assumes there are at least 20 variables
https://github.com/ComputationalScienceLaboratory/ODE-Test-Problems/blob/ca212220284c8c272d4951fdaae4418928ed9f73/src/%2Botp/%2Blorenz96/%2Bpresets/PopovSandu.m#L51

**Comment by AndreyAPopov** [comment]
Oh wow this was so long ago. That preset should probably not have N as a parameter at all, just the number of partitions. It was built with N=40 in mind.

**Comment by AndreyAPopov** [comment]
I will get around to this soon.

**Comment by AndreyAPopov** [comment]
The validation

```
 p.addParameter('Partitions', (mod(N, 4) == 0)*4 + (mod(N, 4) ~= 0)*1, @(x) mod(N, x) == 0); 
```

is actually very simple. It just requires the number of variables to be divisible by the number of partitions, otherwise we get weird effects. The rest just sets the number of partitions to 4 or 1, which is not validation.

The other ones can and will be fixed.

**Comment by Steven-Roberts** [comment]
I was mainly referencing using two inputParsers.  Would it be possible to consolidate into one?

**Comment by AndreyAPopov** [comment]
I guess.
