### ISSUE TITLE
Ode15s as default solver doesn't adhere to error tolerances

### ISSUE THREAD

**Issue by elswit** [ComputationalScienceLaboratory/ODE-Test-Problems#20]
A simple test on Dahlquist:. 

```
model = otp.linear.presets.Dahlquist(-1);
sol = model.solve('Reltol',1e-10, 'Abstol', 1e-10, 'Method', @ode15s);
sol.y(end)-exp(-1)
```

--------
4.162909795304426e-04

if we switch to ode45

`sol = model.solve('Reltol',1e-10, 'Abstol', 1e-10, 'Method', @ode45);`
`sol.y(end)-exp(-1)`

--------
1.209031486038015e-09

**Comment by Steven-Roberts** [comment]
The issue is that the name value pairs are case sensitive.  You need to switch to `RelTol` and `AbsTol`.  I'll see if we can ignore case and give warnings for unused parameters.  Most of this is deferred to `odeset` though.

**Comment by Steven-Roberts** [comment]
The issue boils down to how `odeset` handles struct arguments vs name value pairs.  A simple fix would involve using the function `namedargs2cell`, but this requires MATLAB 2019b.  I guess that's not too new of a version.

**Comment by elswit** [comment]
Ok. It was strange that one integrator worked fine with the lowercase string and the other didn't.  I don't think relying on 2019>  version is unreasonable.

**Comment by Steven-Roberts** [comment]
None of the integrators were passed the tolerances since the capitalization was wrong.  `ode45` just happen to have a very small global error using default tolerances.

**Comment by AndreyAPopov** [comment]
Yeah, silently ignoring options is wrong. We need to warnings everywhere when an option is ignored.
