### ISSUE TITLE
DAE Solver Issues in Octave

### ISSUE THREAD

**Issue by Steven-Roberts** [ComputationalScienceLaboratory/ODE-Test-Problems#42]
For the Ascher linear DAE, the default Octave solver `ode23s` is giving incorrect answers.  Presumably time dependent mass matrix is not well supported. `ode15s` works but breaks for other problems due to `Vectorized` property. Need to reevaluate default stiff/DAE solver for this problem and others.

**Comment by AndreyAPopov** [comment]
Could we solve this by using our own Lobatto IIIC?
