### ISSUE TITLE
Github category as Jupyter notebook instead of matlab

### ISSUE THREAD

**Issue by AndreyAPopov** [ComputationalScienceLaboratory/ODE-Test-Problems#58]
Github is categorizing this project as 80% Jupyter notebook, even though we have thousands of lines of matlab. This is strange, and I am not sure how to fix it.

**Comment by Steven-Roberts** [comment]
The notebook is massive because output including plots is saved. Might be best to remove that. Thoughts @elswit?

**Comment by elswit** [comment]
It is strange, I'll dig to see if we can exclude a directory. The other option is we build the paper/notebooks in a separate repostory

**Comment by elswit** [comment]
Also, another worry of mine is the site we are using to tun  the jupyter notebook recently lost its funding from google so their servers are very slow now. I might have to move to somewhere else.

**Comment by elswit** [comment]
> It is strange, I'll dig to see if we can exclude a directory. The other option is we build the paper/notebooks in a separate repository

Okay I found a fix for it. 
https://github.com/github-linguist/linguist/blob/master/docs/overrides.md#generated-code
