### ISSUE TITLE
Make parameters inherit a base parameter class

### ISSUE THREAD

**Issue by AndreyAPopov** [ComputationalScienceLaboratory/ODE-Test-Problems#64]
The class hierarchy would make more sense if this was the case.

**Comment by Steven-Roberts** [comment]
Is there any shared functionality the base class would provide? If not, I question if it's necessary

**Comment by AndreyAPopov** [comment]
It would help clean up the class hierarchy in the documentation. We can talk about it offline.

**Comment by AndreyAPopov** [comment]
I don't think this is needed anymore. Closing
