### ISSUE TITLE
Consistent Problem Naming 

### ISSUE THREAD

**Issue by Steven-Roberts** [ComputationalScienceLaboratory/ODE-Test-Problems#73]
Some problems have name like "Robertson Problem" with unnecessary "Problem" at end. We should remove this.

**Comment by AndreyAPopov** [comment]
What do you mean? Can you give an example? Robertson is just +robertson

**Comment by Steven-Roberts** [comment]
https://github.com/ComputationalScienceLaboratory/ODE-Test-Problems/blob/5e7814d1eb4e85a222c51bfacee7c9efca2fba32/src/%2Botp/%2Brobertson/RobertsonProblem.m#L29

**Comment by AndreyAPopov** [comment]
Yeah, I see now. This is a problem.
